apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: TimescaleDB
    uid: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true

  - name: Loki
    uid: Loki
    type: loki
    access: proxy
    url: http://loki:3100
